MAX_SEQ_LEN = 20000
UNK_THRESHOLD = 5
BATCH_SIZE = 128
N_EPOCHS = 7
LEARNING_RATE = 1e-3
HIDDEN_DIM = 256
N_RNN_LAYERS = 2

L_RAW, L_LABEL, L_TOKENS = "raw", "label", "text"
PAD = "@@PAD@@"
UNK = "@@UNK@@"